In [8]:
!pip install pandas openpyxl

Requirement already satisfied: pandas in /home/xceland/miniconda3/envs/labbase/lib/python3.11/site-packages (3.0.2)
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: numpy>=1.26.0 in /home/xceland/miniconda3/envs/labbase/lib/python3.11/site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/xceland/miniconda3/envs/labbase/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: six>=1.5 in /home/xceland/miniconda3/envs/labbase/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [openpyxl]━━ 1/2 [openpyxl]
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [5]:
import pandas as pd

In [18]:
from pathlib import Path

print("Current working directory:")
print(Path.cwd())

print("\nExcel files found in this project:")
for file in Path(".").rglob("*.xlsx"):
    print(file)

Current working directory:
/home/xceland/Desktop/Trainingcred Institute/Module 4/labs/python-data-manipulation-database-connectivity

Excel files found in this project:
data/WEOApr2026all.xlsx

In [38]:
# df = pd.read_excel('data/WEOApr2026all.xlsx', sheet_name = 'Countries')
# df = pd.read_excel('data/WEOApr2026all.xlsx', sheet_name = 1)
# df.head()
df = pd.read_excel('data/WEOApr2026all.xlsx', sheet_name = None)
sheet1_df = df['Countries']
sheet1_df.head()

,DATASET,SERIES_CODE,COUNTRY.ID,COUNTRY,INDICATOR.ID,INDICATOR,INDICATOR.Description,FREQUENCY,SCALE,UNIT,...,2022,2023,2024,2025,2026,2027,2028,2029,2030,2031
0,IMF.RES:WEO(9.0.0),AND.NGDP_R.A,AND,"Andorra, Principality of",NGDP_R,"Gross domestic product (GDP), Constant prices,...",Gross domestic product reflects the total inco...,Annual,Billions,Domestic currency,...,2.818,2.891,3.002,3.119,3.185,3.243,3.299,3.351,3.402,3.453
1,IMF.RES:WEO(9.0.0),AND.NGDP_RPCH.A,AND,"Andorra, Principality of",NGDP_RPCH,"Gross domestic product (GDP), Constant prices,...",Gross domestic product reflects the total inco...,Annual,Units,Percent,...,9.565,2.584,3.849,3.900,2.100,1.840,1.700,1.600,1.500,1.500
2,IMF.RES:WEO(9.0.0),AND.NGDP.A,AND,"Andorra, Principality of",NGDP,"Gross domestic product (GDP), Current prices, ...",Gross domestic product reflects the total inco...,Annual,Billions,Domestic currency,...,3.210,3.501,3.736,3.983,4.181,4.351,4.514,4.678,4.843,5.014
3,IMF.RES:WEO(9.0.0),AND.NGDPD.A,AND,"Andorra, Principality of",NGDPD,"Gross domestic product (GDP), Current prices, ...",Gross domestic product reflects the total inco...,Annual,Billions,US dollar,...,3.376,3.786,4.042,4.491,4.879,5.065,5.245,5.430,5.617,5.878
4,IMF.RES:WEO(9.0.0),AND.PPPGDP.A,AND,"Andorra, Principality of",PPPGDP,"Gross domestic product (GDP), Current prices, ...",Gross domestic product reflects the total inco...,Annual,Billions,NaN,...,5.457,5.805,6.178,6.601,6.932,7.215,7.458,7.712,7.972,8.237

In [51]:
df = pd.read_excel('data/WEOApr2026all.xlsx', sheet_name = 1,usecols='A:C', skiprows=2, skipfooter=3)
df.head()

   IMF.RES:WEO(9.0.0) AND.NGDP_RPCH.A  AND
0  IMF.RES:WEO(9.0.0)      AND.NGDP.A  AND
1  IMF.RES:WEO(9.0.0)     AND.NGDPD.A  AND
2  IMF.RES:WEO(9.0.0)    AND.PPPGDP.A  AND
3  IMF.RES:WEO(9.0.0)    AND.NGDP_D.A  AND
4  IMF.RES:WEO(9.0.0)   AND.NGDPRPC.A  AND

In [52]:
import pandas as pd

# Load data while skipping the last 3 rows (adjust number if needed)
df = pd.read_excel(
    'data/WEOApr2026all.xlsx', 
    sheet_name=1, 
    usecols=['DATASET', 'SERIES_CODE'],
    skipfooter=3
)

# View the last few rows to confirm metadata is gone
print(df.tail())

                 DATASET         SERIES_CODE
8660  IMF.RES:WEO(9.0.0)  ZWE.GGXONLB_NGDP.A
8661  IMF.RES:WEO(9.0.0)        ZWE.GGXWDN.A
8662  IMF.RES:WEO(9.0.0)   ZWE.GGXWDN_NGDP.A
8663  IMF.RES:WEO(9.0.0)        ZWE.GGXWDG.A
8664  IMF.RES:WEO(9.0.0)   ZWE.GGXWDG_NGDP.A

In [47]:
df = pd.read_excel('data/WEOApr2026all.xlsx', sheet_name = 1,usecols=['DATASET','SERIES_CODE'])
df.head()

              DATASET      SERIES_CODE
0  IMF.RES:WEO(9.0.0)     AND.NGDP_R.A
1  IMF.RES:WEO(9.0.0)  AND.NGDP_RPCH.A
2  IMF.RES:WEO(9.0.0)       AND.NGDP.A
3  IMF.RES:WEO(9.0.0)      AND.NGDPD.A
4  IMF.RES:WEO(9.0.0)     AND.PPPGDP.A

In [39]:
df['Countries'].head()

,DATASET,SERIES_CODE,COUNTRY.ID,COUNTRY,INDICATOR.ID,INDICATOR,INDICATOR.Description,FREQUENCY,SCALE,UNIT,...,2022,2023,2024,2025,2026,2027,2028,2029,2030,2031
0,IMF.RES:WEO(9.0.0),AND.NGDP_R.A,AND,"Andorra, Principality of",NGDP_R,"Gross domestic product (GDP), Constant prices,...",Gross domestic product reflects the total inco...,Annual,Billions,Domestic currency,...,2.818,2.891,3.002,3.119,3.185,3.243,3.299,3.351,3.402,3.453
1,IMF.RES:WEO(9.0.0),AND.NGDP_RPCH.A,AND,"Andorra, Principality of",NGDP_RPCH,"Gross domestic product (GDP), Constant prices,...",Gross domestic product reflects the total inco...,Annual,Units,Percent,...,9.565,2.584,3.849,3.900,2.100,1.840,1.700,1.600,1.500,1.500
2,IMF.RES:WEO(9.0.0),AND.NGDP.A,AND,"Andorra, Principality of",NGDP,"Gross domestic product (GDP), Current prices, ...",Gross domestic product reflects the total inco...,Annual,Billions,Domestic currency,...,3.210,3.501,3.736,3.983,4.181,4.351,4.514,4.678,4.843,5.014
3,IMF.RES:WEO(9.0.0),AND.NGDPD.A,AND,"Andorra, Principality of",NGDPD,"Gross domestic product (GDP), Current prices, ...",Gross domestic product reflects the total inco...,Annual,Billions,US dollar,...,3.376,3.786,4.042,4.491,4.879,5.065,5.245,5.430,5.617,5.878
4,IMF.RES:WEO(9.0.0),AND.PPPGDP.A,AND,"Andorra, Principality of",PPPGDP,"Gross domestic product (GDP), Current prices, ...",Gross domestic product reflects the total inco...,Annual,Billions,NaN,...,5.457,5.805,6.178,6.601,6.932,7.215,7.458,7.712,7.972,8.237

In [ ]:
for sheet_name, df2 in df.items():
    print(f"--- Sheet Name: {sheet_name} ---")
    print(df1.head(2))
    print("\n")

--- Sheet Name: April 2026 WEO ---
   Unnamed: 0 Unnamed: 1  Unnamed: 2  Unnamed: 3  Unnamed: 4  Unnamed: 5  \
0         NaN        NaN         NaN         NaN         NaN         NaN
1         NaN        NaN         NaN         NaN         NaN         NaN

   Unnamed: 6  Unnamed: 7 Unnamed: 8
0         NaN         NaN        NaT
1         NaN         NaN 2026-04-14


--- Sheet Name: Countries ---
              DATASET      SERIES_CODE COUNTRY.ID                   COUNTRY  \
0  IMF.RES:WEO(9.0.0)     AND.NGDP_R.A        AND  Andorra, Principality of
1  IMF.RES:WEO(9.0.0)  AND.NGDP_RPCH.A        AND  Andorra, Principality of

  INDICATOR.ID                                          INDICATOR  \
0       NGDP_R  Gross domestic product (GDP), Constant prices,...
1    NGDP_RPCH  Gross domestic product (GDP), Constant prices,...

                               INDICATOR.Description FREQUENCY     SCALE  \
0  Gross domestic product reflects the total inco...    Annual  Billions
1  Gross domestic product reflects the total inco...    Annual     Units

                UNIT  ...   2022   2023   2024   2025   2026   2027   2028  \
0  Domestic currency  ...  2.818  2.891  3.002  3.119  3.185  3.243  3.299
1            Percent  ...  9.565  2.584  3.849  3.900  2.100  1.840  1.700

    2029   2030   2031
0  3.351  3.402  3.453
1  1.600  1.500  1.500

[2 rows x 81 columns]


--- Sheet Name: Country Groups ---
              DATASET         SERIES_CODE COUNTRY.ID COUNTRY INDICATOR.ID  \
0  IMF.RES:WEO(9.0.0)    G001.NGDP_RPCH.A       G001   World    NGDP_RPCH
1  IMF.RES:WEO(9.0.0)  G001.NGDP_RPCHMK.A       G001   World  NGDP_RPCHMK

                                           INDICATOR  \
0  Gross domestic product (GDP), Constant prices,...
1  Gross domestic product (GDP), Constant prices,...

                               INDICATOR.Description FREQUENCY  SCALE  \
0  Gross domestic product reflects the total inco...    Annual  Units
1  Gross domestic product reflects the total inco...    Annual  Units

      UNIT  ...   2022   2023   2024   2025   2026   2027   2028   2029  \
0  Percent  ...  3.774  3.328  3.416  3.441  3.056  3.224  3.240  3.161
1  Percent  ...  3.383  2.826  2.870  2.863  2.564  2.640  2.647  2.530

    2030   2031
0  3.074  3.071
1  2.438  2.430

[2 rows x 81 columns]


--- Sheet Name: Commodity Prices ---
              DATASET      SERIES_CODE COUNTRY.ID COUNTRY INDICATOR.ID  \
0  IMF.RES:WEO(9.0.0)  G001.PALLFNFW.A       G001   World     PALLFNFW
1  IMF.RES:WEO(9.0.0)   G001.PNFUELW.A       G001   World      PNFUELW

                                INDICATOR  \
0  All commodities, Commodity price index
1         Non-fuel, Commodity price index

                               INDICATOR.Description FREQUENCY  SCALE   UNIT  \
0  All Commodity Price Index, 2016 = 100, include...    Annual  Units  Index
1  Non-Fuel Price Index, 2016 = 100, includes Pre...    Annual  Units  Index

   ...     2022     2023     2024     2025     2026     2027     2028  \
0  ...  215.917  165.648  164.822  166.946  201.390  197.778  193.867
1  ...  158.125  149.155  154.672  169.579  206.407  210.392  210.919

      2029     2030     2031
0  191.877  191.536  191.311
1  209.669  209.603  209.644

[2 rows x 81 columns]


--- Sheet Name: Country Group Composition ---
  groupcode groupname  groupcode_previous countrycode  \
0      G001     World                   1         AFG
1      G001     World                   1         ALB

                        countryname  countrycode_previous
0  Afghanistan, Islamic Republic of                   512
1                           Albania                   914

In [42]:
print(df.keys())

dict_keys(['April 2026 WEO', 'Countries', 'Country Groups', 'Commodity Prices', 'Country Group Composition'])

In [45]:
combined_df = pd.concat(df.values(), ignore_index=True)
combined_df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,DATASET,...,2029,2030,2031,METHODOLOGY,groupcode,groupname,groupcode_previous,countrycode,countryname,countrycode_previous
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-04-14,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,International Monetary Fund,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,World Economic Outlook Database,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df = pd.read_json('data.json')
print(df.to_string)

In [54]:
df.tail(10)

                 DATASET         SERIES_CODE
8655  IMF.RES:WEO(9.0.0)        ZWE.GGXCNL.A
8656  IMF.RES:WEO(9.0.0)   ZWE.GGXCNL_NGDP.A
8657  IMF.RES:WEO(9.0.0)          ZWE.GGSB.A
8658  IMF.RES:WEO(9.0.0)    ZWE.GGSB_NPGDP.A
8659  IMF.RES:WEO(9.0.0)       ZWE.GGXONLB.A
8660  IMF.RES:WEO(9.0.0)  ZWE.GGXONLB_NGDP.A
8661  IMF.RES:WEO(9.0.0)        ZWE.GGXWDN.A
8662  IMF.RES:WEO(9.0.0)   ZWE.GGXWDN_NGDP.A
8663  IMF.RES:WEO(9.0.0)        ZWE.GGXWDG.A
8664  IMF.RES:WEO(9.0.0)   ZWE.GGXWDG_NGDP.A

In [55]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8665 entries, 0 to 8664
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   DATASET      8665 non-null   str
 1   SERIES_CODE  8665 non-null   str
dtypes: str(2)
memory usage: 135.5 KB