In [2]:
import pandas as pd

In [3]:
df = pd.read_excel('data/WEOApr2026all.xlsx', sheet_name = None)
sheet1_df = df['Countries']
sheet1_df.head()

,DATASET,SERIES_CODE,COUNTRY.ID,COUNTRY,INDICATOR.ID,INDICATOR,INDICATOR.Description,FREQUENCY,SCALE,UNIT,...,2022,2023,2024,2025,2026,2027,2028,2029,2030,2031
0,IMF.RES:WEO(9.0.0),AND.NGDP_R.A,AND,"Andorra, Principality of",NGDP_R,"Gross domestic product (GDP), Constant prices,...",Gross domestic product reflects the total inco...,Annual,Billions,Domestic currency,...,2.818,2.891,3.002,3.119,3.185,3.243,3.299,3.351,3.402,3.453
1,IMF.RES:WEO(9.0.0),AND.NGDP_RPCH.A,AND,"Andorra, Principality of",NGDP_RPCH,"Gross domestic product (GDP), Constant prices,...",Gross domestic product reflects the total inco...,Annual,Units,Percent,...,9.565,2.584,3.849,3.900,2.100,1.840,1.700,1.600,1.500,1.500
2,IMF.RES:WEO(9.0.0),AND.NGDP.A,AND,"Andorra, Principality of",NGDP,"Gross domestic product (GDP), Current prices, ...",Gross domestic product reflects the total inco...,Annual,Billions,Domestic currency,...,3.210,3.501,3.736,3.983,4.181,4.351,4.514,4.678,4.843,5.014
3,IMF.RES:WEO(9.0.0),AND.NGDPD.A,AND,"Andorra, Principality of",NGDPD,"Gross domestic product (GDP), Current prices, ...",Gross domestic product reflects the total inco...,Annual,Billions,US dollar,...,3.376,3.786,4.042,4.491,4.879,5.065,5.245,5.430,5.617,5.878
4,IMF.RES:WEO(9.0.0),AND.PPPGDP.A,AND,"Andorra, Principality of",PPPGDP,"Gross domestic product (GDP), Current prices, ...",Gross domestic product reflects the total inco...,Annual,Billions,NaN,...,5.457,5.805,6.178,6.601,6.932,7.215,7.458,7.712,7.972,8.237

In [5]:
sheet1_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8668 entries, 0 to 8667
Data columns (total 81 columns):
 #   Column                                                    Non-Null Count  Dtype
---  ------                                                    --------------  -----
 0   DATASET                                                   8668 non-null   str
 1   SERIES_CODE                                               8668 non-null   str
 2   COUNTRY.ID                                                8668 non-null   str
 3   COUNTRY                                                   8668 non-null   str
 4   INDICATOR.ID                                              8668 non-null   str
 5   INDICATOR                                                 8668 non-null   str
 6   INDICATOR.Description                                     8668 non-null   str
 7   FREQUENCY                                                 8668 non-null   str
 8   SCALE                                                     7670 non-null   str
 9   UNIT                                                      6528 non-null   str
 10  COUNTRY_UPDATE_DATE                                       7595 non-null   datetime64[us]
 11  PUBLICATION_DATE                                          8668 non-null   str
 12  UPDATE_DATE                                               8668 non-null   str
 13  METHODOLOGY.ID                                            5030 non-null   str
 14  METHODOLOGY_NOTES                                         5403 non-null   str
 15  LATEST_ACTUAL_ANNUAL_DATA                                 6879 non-null   object
 16  HISTORICAL_DATA_SOURCE                                    6879 non-null   str
 17  BASE_YEAR                                                 3808 non-null   object
 18  START_END_MONTHS_OF_REPORTING_YEAR                        4638 non-null   str
 19  CHAIN_WEIGHTED                                            3018 non-null   str
 20  BASIS_OF_PROJECTIONS                                      1813 non-null   str
 21  VALUATION                                                 2299 non-null   str
 22  PRICES_SECTOR_HARMONIZED_PRICES                           786 non-null    str
 23  LABOR_SECTOR_EMPLOYMENT_TYPE                              158 non-null    str
 24  FISCAL_SECTOR_GENERAL_GOVERNMENT_COMPOSITION              2287 non-null   str
 25  FISCAL_SECTOR_VALUATION_OF_DEBT                           2267 non-null   str
 26  FISCAL_SECTOR_INSTRUMENTS_INCLUDED_IN_GROSS_AND_NET_DEBT  1896 non-null   str
 27  TRADE_SECTOR_OIL_COVERAGE                                 615 non-null    str
 28  PRIMARY_DOMESTIC_CURRENCY                                 6879 non-null   str
 29  1980                                                      3798 non-null   float64
 30  1981                                                      3941 non-null   float64
 31  1982                                                      3985 non-null   float64
 32  1983                                                      4029 non-null   float64
 33  1984                                                      4054 non-null   float64
 34  1985                                                      4135 non-null   float64
 35  1986                                                      4188 non-null   float64
 36  1987                                                      4220 non-null   float64
 37  1988                                                      4300 non-null   float64
 38  1989                                                      4371 non-null   float64
 39  1990                                                      4838 non-null   float64
 40  1991                                                      5021 non-null   float64
 41  1992                                                      5382 non-null   float64
 42  1993                                                      5576 non-null   float64
 43  1994                                                      5707 non-null   float64
 44  1995                                                      6056 non-null   float64
 45  1996                                                      6184 non-null   float64
 46  1997                                                      6352 non-null   float64
 47  1998                                                      6510 non-null   float64
 48  1999                                                      6606 non-null   float64
 49  2000                                                      7053 non-null   float64
 50  2001                                                      7207 non-null   float64
 51  2002                                                      7300 non-null   float64
 52  2003                                                      7328 non-null   float64
 53  2004                                                      7401 non-null   float64
 54  2005                                                      7432 non-null   float64
 55  2006                                                      7440 non-null   float64
 56  2007                                                      7444 non-null   float64
 57  2008                                                      7453 non-null   float64
 58  2009                                                      7475 non-null   float64
 59  2010                                                      7489 non-null   float64
 60  2011                                                      7501 non-null   float64
 61  2012                                                      7523 non-null   float64
 62  2013                                                      7539 non-null   float64
 63  2014                                                      7584 non-null   float64
 64  2015                                                      7600 non-null   float64
 65  2016                                                      7602 non-null   float64
 66  2017                                                      7612 non-null   float64
 67  2018                                                      7622 non-null   float64
 68  2019                                                      7620 non-null   float64
 69  2020                                                      7585 non-null   float64
 70  2021                                                      7585 non-null   float64
 71  2022                                                      7585 non-null   float64
 72  2023                                                      7576 non-null   float64
 73  2024                                                      7573 non-null   float64
 74  2025                                                      7504 non-null   float64
 75  2026                                                      7385 non-null   float64
 76  2027                                                      7346 non-null   float64
 77  2028                                                      7262 non-null   float64
 78  2029                                                      7257 non-null   float64
 79  2030                                                      7257 non-null   float64
 80  2031                                                      7257 non-null   float64
dtypes: datetime64[us](1), float64(52), object(2), str(26)
memory usage: 5.4+ MB

In [7]:
new_df = sheet1_df.dropna()
sheet1_df.dropna(inplace = True)

In [10]:
sheet1_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8668 entries, 0 to 8667
Data columns (total 81 columns):
 #   Column                                                    Non-Null Count  Dtype
---  ------                                                    --------------  -----
 0   DATASET                                                   8668 non-null   str
 1   SERIES_CODE                                               8668 non-null   str
 2   COUNTRY.ID                                                8668 non-null   str
 3   COUNTRY                                                   8668 non-null   str
 4   INDICATOR.ID                                              8668 non-null   str
 5   INDICATOR                                                 8668 non-null   str
 6   INDICATOR.Description                                     8668 non-null   str
 7   FREQUENCY                                                 8668 non-null   str
 8   SCALE                                                     7670 non-null   str
 9   UNIT                                                      6528 non-null   str
 10  COUNTRY_UPDATE_DATE                                       7595 non-null   datetime64[us]
 11  PUBLICATION_DATE                                          8668 non-null   str
 12  UPDATE_DATE                                               8668 non-null   str
 13  METHODOLOGY.ID                                            5030 non-null   str
 14  METHODOLOGY_NOTES                                         5403 non-null   str
 15  LATEST_ACTUAL_ANNUAL_DATA                                 6879 non-null   object
 16  HISTORICAL_DATA_SOURCE                                    6879 non-null   str
 17  BASE_YEAR                                                 3808 non-null   object
 18  START_END_MONTHS_OF_REPORTING_YEAR                        4638 non-null   str
 19  CHAIN_WEIGHTED                                            3018 non-null   str
 20  BASIS_OF_PROJECTIONS                                      1813 non-null   str
 21  VALUATION                                                 2299 non-null   str
 22  PRICES_SECTOR_HARMONIZED_PRICES                           786 non-null    str
 23  LABOR_SECTOR_EMPLOYMENT_TYPE                              158 non-null    str
 24  FISCAL_SECTOR_GENERAL_GOVERNMENT_COMPOSITION              2287 non-null   str
 25  FISCAL_SECTOR_VALUATION_OF_DEBT                           2267 non-null   str
 26  FISCAL_SECTOR_INSTRUMENTS_INCLUDED_IN_GROSS_AND_NET_DEBT  1896 non-null   str
 27  TRADE_SECTOR_OIL_COVERAGE                                 615 non-null    str
 28  PRIMARY_DOMESTIC_CURRENCY                                 6879 non-null   str
 29  1980                                                      3798 non-null   float64
 30  1981                                                      3941 non-null   float64
 31  1982                                                      3985 non-null   float64
 32  1983                                                      4029 non-null   float64
 33  1984                                                      4054 non-null   float64
 34  1985                                                      4135 non-null   float64
 35  1986                                                      4188 non-null   float64
 36  1987                                                      4220 non-null   float64
 37  1988                                                      4300 non-null   float64
 38  1989                                                      4371 non-null   float64
 39  1990                                                      4838 non-null   float64
 40  1991                                                      5021 non-null   float64
 41  1992                                                      5382 non-null   float64
 42  1993                                                      5576 non-null   float64
 43  1994                                                      5707 non-null   float64
 44  1995                                                      6056 non-null   float64
 45  1996                                                      6184 non-null   float64
 46  1997                                                      6352 non-null   float64
 47  1998                                                      6510 non-null   float64
 48  1999                                                      6606 non-null   float64
 49  2000                                                      7053 non-null   float64
 50  2001                                                      7207 non-null   float64
 51  2002                                                      7300 non-null   float64
 52  2003                                                      7328 non-null   float64
 53  2004                                                      7401 non-null   float64
 54  2005                                                      7432 non-null   float64
 55  2006                                                      7440 non-null   float64
 56  2007                                                      7444 non-null   float64
 57  2008                                                      7453 non-null   float64
 58  2009                                                      7475 non-null   float64
 59  2010                                                      7489 non-null   float64
 60  2011                                                      7501 non-null   float64
 61  2012                                                      7523 non-null   float64
 62  2013                                                      7539 non-null   float64
 63  2014                                                      7584 non-null   float64
 64  2015                                                      7600 non-null   float64
 65  2016                                                      7602 non-null   float64
 66  2017                                                      7612 non-null   float64
 67  2018                                                      7622 non-null   float64
 68  2019                                                      7620 non-null   float64
 69  2020                                                      7585 non-null   float64
 70  2021                                                      7585 non-null   float64
 71  2022                                                      7585 non-null   float64
 72  2023                                                      7576 non-null   float64
 73  2024                                                      7573 non-null   float64
 74  2025                                                      7504 non-null   float64
 75  2026                                                      7385 non-null   float64
 76  2027                                                      7346 non-null   float64
 77  2028                                                      7262 non-null   float64
 78  2029                                                      7257 non-null   float64
 79  2030                                                      7257 non-null   float64
 80  2031                                                      7257 non-null   float64
dtypes: datetime64[us](1), float64(52), object(2), str(26)
memory usage: 5.4+ MB

In [11]:
sheet1_df.fillna({"SCALE": "No VALUE"}, inplace =True)

,DATASET,SERIES_CODE,COUNTRY.ID,COUNTRY,INDICATOR.ID,INDICATOR,INDICATOR.Description,FREQUENCY,SCALE,UNIT,...,2022,2023,2024,2025,2026,2027,2028,2029,2030,2031
0,IMF.RES:WEO(9.0.0),AND.NGDP_R.A,AND,"Andorra, Principality of",NGDP_R,"Gross domestic product (GDP), Constant prices,...",Gross domestic product reflects the total inco...,Annual,Billions,Domestic currency,...,2.818,2.891,3.002,3.119,3.185,3.243,3.299,3.351,3.402,3.453
1,IMF.RES:WEO(9.0.0),AND.NGDP_RPCH.A,AND,"Andorra, Principality of",NGDP_RPCH,"Gross domestic product (GDP), Constant prices,...",Gross domestic product reflects the total inco...,Annual,Units,Percent,...,9.565,2.584,3.849,3.900,2.100,1.840,1.700,1.600,1.500,1.500
2,IMF.RES:WEO(9.0.0),AND.NGDP.A,AND,"Andorra, Principality of",NGDP,"Gross domestic product (GDP), Current prices, ...",Gross domestic product reflects the total inco...,Annual,Billions,Domestic currency,...,3.210,3.501,3.736,3.983,4.181,4.351,4.514,4.678,4.843,5.014
3,IMF.RES:WEO(9.0.0),AND.NGDPD.A,AND,"Andorra, Principality of",NGDPD,"Gross domestic product (GDP), Current prices, ...",Gross domestic product reflects the total inco...,Annual,Billions,US dollar,...,3.376,3.786,4.042,4.491,4.879,5.065,5.245,5.430,5.617,5.878
4,IMF.RES:WEO(9.0.0),AND.PPPGDP.A,AND,"Andorra, Principality of",PPPGDP,"Gross domestic product (GDP), Current prices, ...",Gross domestic product reflects the total inco...,Annual,Billions,NaN,...,5.457,5.805,6.178,6.601,6.932,7.215,7.458,7.712,7.972,8.237
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8663,IMF.RES:WEO(9.0.0),ZWE.GGXWDG.A,ZWE,Zimbabwe,GGXWDG,"Gross debt, General government, Domestic currency",Gross debt is the sum of all liabilities that ...,Annual,Billions,Domestic currency,...,4.932,51.431,579.186,625.331,719.150,790.394,869.236,955.641,1050.631,1155.182
8664,IMF.RES:WEO(9.0.0),ZWE.GGXWDG_NGDP.A,ZWE,Zimbabwe,GGXWDG_NGDP,"Gross debt, General government, Percent of GDP",Gross debt is the sum of all liabilities that ...,Annual,Units,Percent,...,66.789,76.127,70.380,43.765,42.333,41.355,40.403,39.454,38.521,37.608
8665,IMF.RES:WEO(9.0.0),ZWE.NGDP_FY.A,ZWE,Zimbabwe,NGDP_FY,"Gross domestic product (GDP), Current prices, ...",Gross domestic product reflects the total inco...,Annual,Billions,Domestic currency,...,7.384,67.559,822.938,1428.821,1698.800,1911.225,2151.433,2422.166,2727.410,3071.623
8666,IMF.RES:WEO(9.0.0),ZWE.BCA.A,ZWE,Zimbabwe,BCA,"Current account balance (credit less debit), U...",The current account balance is the balance of ...,Annual,Billions,US dollar,...,0.305,0.135,0.501,2.129,2.120,1.994,1.796,1.628,1.371,1.016
8667,IMF.RES:WEO(9.0.0),ZWE.BCA_NGDPD.A,ZWE,Zimbabwe,BCA_NGDPD,"Current account balance (credit less debit), P...",The current account balance is the balance of ...,Annual,Units,Percent,...,0.628,0.304,1.020,3.982,3.738,3.474,3.003,2.611,2.110,1.500

In [ ]:
sheet1_df.fillna({"SCALE": "No VALUE"}, inplace =True)

In [14]:
for sheetName, dfName in df.items():
    print({sheetName})
    # print(dfName.head(2))

{'April 2026 WEO'}
{'Countries'}
{'Country Groups'}
{'Commodity Prices'}
{'Country Group Composition'}

In [18]:
sheet3_df = df['Commodity Prices']

In [20]:
sheet3_df.head()

,DATASET,SERIES_CODE,COUNTRY.ID,COUNTRY,INDICATOR.ID,INDICATOR,INDICATOR.Description,FREQUENCY,SCALE,UNIT,...,2022,2023,2024,2025,2026,2027,2028,2029,2030,2031
0,IMF.RES:WEO(9.0.0),G001.PALLFNFW.A,G001,World,PALLFNFW,"All commodities, Commodity price index","All Commodity Price Index, 2016 = 100, include...",Annual,Units,Index,...,215.917,165.648,164.822,166.946,201.390,197.778,193.867,191.877,191.536,191.311
1,IMF.RES:WEO(9.0.0),G001.PNFUELW.A,G001,World,PNFUELW,"Non-fuel, Commodity price index","Non-Fuel Price Index, 2016 = 100, includes Pre...",Annual,Units,Index,...,158.125,149.155,154.672,169.579,206.407,210.392,210.919,209.669,209.603,209.644
2,IMF.RES:WEO(9.0.0),G001.PINDUW.A,G001,World,PINDUW,"Industrial materials, Commodity price index","Industrial Inputs Price Index, 2016 = 100, inc...",Annual,Units,Index,...,172.847,163.714,162.410,164.599,190.542,190.857,189.607,188.258,187.960,188.113
3,IMF.RES:WEO(9.0.0),G001.POILAPSP.A,G001,World,POILAPSP,"APSP crude oil, Unit prices, US dollars per ba...","Crude Oil (petroleum), Price index, 2016 = 100...",Annual,Units,US dollar per barrel,...,96.362,80.595,79.171,67.737,82.218,75.966,74.235,73.910,73.690,73.306
4,IMF.RES:WEO(9.0.0),G001.POILBRE.A,G001,World,POILBRE,"Brent crude, Unit prices, US dollars per barrel","Crude Oil (petroleum), Dated Brent, light blen...",Annual,Units,US dollar per barrel,...,98.996,82.321,79.912,68.325,80.187,71.452,69.690,69.423,69.358,69.127

In [22]:
list(sheet3_df.columns)

['DATASET',
 'SERIES_CODE',
 'COUNTRY.ID',
 'COUNTRY',
 'INDICATOR.ID',
 'INDICATOR',
 'INDICATOR.Description',
 'FREQUENCY',
 'SCALE',
 'UNIT',
 'COUNTRY_UPDATE_DATE',
 'PUBLICATION_DATE',
 'UPDATE_DATE',
 'METHODOLOGY',
 'METHODOLOGY_NOTES',
 'LATEST_ACTUAL_ANNUAL_DATA',
 'HISTORICAL_DATA_SOURCE',
 'BASE_YEAR',
 'START_END_MONTHS_OF_REPORTING_YEAR',
 'CHAIN_WEIGHTED',
 'BASIS_OF_PROJECTIONS',
 'VALUATION',
 'PRICES_SECTOR_HARMONIZED_PRICES',
 'LABOR_SECTOR_EMPLOYMENT_TYPE',
 'FISCAL_SECTOR_GENERAL_GOVERNMENT_COMPOSITION',
 'FISCAL_SECTOR_VALUATION_OF_DEBT',
 'FISCAL_SECTOR_INSTRUMENTS_INCLUDED_IN_GROSS_AND_NET_DEBT',
 'TRADE_SECTOR_OIL_COVERAGE',
 'PRIMARY_DOMESTIC_CURRENCY',
 1980,
 1981,
 1982,
 1983,
 1984,
 1985,
 1986,
 1987,
 1988,
 1989,
 1990,
 1991,
 1992,
 1993,
 1994,
 1995,
 1996,
 1997,
 1998,
 1999,
 2000,
 2001,
 2002,
 2003,
 2004,
 2005,
 2006,
 2007,
 2008,
 2009,
 2010,
 2011,
 2012,
 2013,
 2014,
 2015,
 2016,
 2017,
 2018,
 2019,
 2020,
 2021,
 2022,
 2023,
 2024,
 2025,
 2026,
 2027,
 2028,
 2029,
 2030,
 2031]

In [23]:
sheet3_df.dtypes

DATASET             str
SERIES_CODE         str
COUNTRY.ID          str
COUNTRY             str
INDICATOR.ID        str
                 ...
2027            float64
2028            float64
2029            float64
2030            float64
2031            float64
Length: 81, dtype: object

In [31]:
mean = sheet3_df[2022].mean()
median = sheet3_df[2022].median()
mode = sheet3_df[2022].mode()[0]
mode = sheet3_df[2022].mode().iloc[0]

print(f"Mean: {mean}")
print(f"Median: {median}")
print(f"Mode: {mode}")

Mean: 1414.3164000000002
Median: 209.114
Mode: 1.751

In [30]:
# sheet3_df.fillna({2022: mean, inplace=True)
sheet3_df[2022] = sheet3_df[2022].fillna(mean)

In [32]:
cols = [2020, 2021, 2022]

sheet3_df[cols] = sheet3_df[cols].fillna(sheet3_df[cols].mean())
sheet3_df[cols] = sheet3_df[cols].fillna(sheet3_df[cols].mode())

In [33]:
cols = [2020, 2021, 2022]
sheet3_df[cols] = sheet3_df[cols].fillna(sheet3_df[cols].mode())

In [ ]:
cols = ["COUNTRY", "Region", "Status"]
modes = sheet3_df[cols].mode().iloc[0]
sheet3_df[cols] = sheet3_df[cols].fillna(modes)

cols = ["Country", "Region", "Status"]
sheet3_df[cols] = sheet3_df[cols].fillna("Unknown")

In [36]:
string_cols = sheet3_df.select_dtypes(include="object").columns
print(string_cols)
num_cols = sheet3_df.select_dtypes(include="float").columns
print(num_cols)

Index(['DATASET', 'SERIES_CODE', 'COUNTRY.ID', 'COUNTRY', 'INDICATOR.ID',
       'INDICATOR', 'INDICATOR.Description', 'FREQUENCY', 'SCALE', 'UNIT',
       'PUBLICATION_DATE', 'UPDATE_DATE'],
      dtype='object')
Index([                                     'COUNTRY_UPDATE_DATE',
                                                    'METHODOLOGY',
                                              'METHODOLOGY_NOTES',
                                      'LATEST_ACTUAL_ANNUAL_DATA',
                                         'HISTORICAL_DATA_SOURCE',
                                                      'BASE_YEAR',
                             'START_END_MONTHS_OF_REPORTING_YEAR',
                                                 'CHAIN_WEIGHTED',
                                           'BASIS_OF_PROJECTIONS',
                                                      'VALUATION',
                                'PRICES_SECTOR_HARMONIZED_PRICES',
                                   'LABOR_SECTOR_EMPLOYMENT_TYPE',
                   'FISCAL_SECTOR_GENERAL_GOVERNMENT_COMPOSITION',
                                'FISCAL_SECTOR_VALUATION_OF_DEBT',
       'FISCAL_SECTOR_INSTRUMENTS_INCLUDED_IN_GROSS_AND_NET_DEBT',
                                      'TRADE_SECTOR_OIL_COVERAGE',
                                      'PRIMARY_DOMESTIC_CURRENCY',
                                                             1980,
                                                             1981,
                                                             1982,
                                                             1983,
                                                             1984,
                                                             1985,
                                                             1986,
                                                             1987,
                                                             1988,
                                                             1989,
                                                             1990,
                                                             1991,
                                                             1992,
                                                             1993,
                                                             1994,
                                                             1995,
                                                             1996,
                                                             1997,
                                                             1998,
                                                             1999,
                                                             2000,
                                                             2001,
                                                             2002,
                                                             2003,
                                                             2004,
                                                             2005,
                                                             2006,
                                                             2007,
                                                             2008,
                                                             2009,
                                                             2010,
                                                             2011,
                                                             2012,
                                                             2013,
                                                             2014,
                                                             2015,
                                                             2016,
                                                             2017,
                                                             2018,
                                                             2019,
                                                             2020,
                                                             2021,
                                                             2022,
                                                             2023,
                                                             2024,
                                                             2025,
                                                             2026,
                                                             2027,
                                                             2028,
                                                             2029,
                                                             2030,
                                                             2031],
      dtype='object')

/tmp/ipykernel_78525/2616495347.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  string_cols = sheet3_df.select_dtypes(include="object").columns

In [39]:
# Apply only to all string columns automatically
sheet3_df[string_cols] = sheet3_df[string_cols].fillna("Unknown")

In [40]:
# Or using each column’s own mode
sheet3_df[string_cols] = sheet3_df[string_cols].fillna(sheet3_df[string_cols].mode().iloc[0])

In [41]:
sheet3_df['PUBLICATION_DATE'] = pd.to_datetime(sheet3_df['PUBLICATION_DATE'], format = 'mixed')
print(sheet3_df['PUBLICATION_DATE'].to_string)

<bound method Series.to_string of 0    2026-04-14 13:00:00+00:00
1    2026-04-14 13:00:00+00:00
2    2026-04-14 13:00:00+00:00
3    2026-04-14 13:00:00+00:00
4    2026-04-14 13:00:00+00:00
                ...
70   2026-04-14 13:00:00+00:00
71   2026-04-14 13:00:00+00:00
72   2026-04-14 13:00:00+00:00
73   2026-04-14 13:00:00+00:00
74   2026-04-14 13:00:00+00:00
Name: PUBLICATION_DATE, Length: 75, dtype: datetime64[us, UTC]>

In [43]:
sheet3_df.dropna(subset = ['PUBLICATION_DATE'], inplace = True)

In [ ]:
sheet3_df.loc[7, ''] = 45

In [ ]:
for x in df.index:
  if df.loc[x, "Duration"] > 120:
    df.drop(x, inplace = True)

In [45]:
print(sheet3_df.duplicated())

0     False
1     False
2     False
3     False
4     False
      ...
70    False
71    False
72    False
73    False
74    False
Length: 75, dtype: bool

In [46]:
sheet3_df.drop_duplicates(inplace = True)

In [53]:
sheet3_df.corr(numeric_only=True)

,COUNTRY_UPDATE_DATE,METHODOLOGY,METHODOLOGY_NOTES,LATEST_ACTUAL_ANNUAL_DATA,HISTORICAL_DATA_SOURCE,BASE_YEAR,START_END_MONTHS_OF_REPORTING_YEAR,CHAIN_WEIGHTED,BASIS_OF_PROJECTIONS,VALUATION,...,2022,2023,2024,2025,2026,2027,2028,2029,2030,2031
COUNTRY_UPDATE_DATE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
METHODOLOGY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
METHODOLOGY_NOTES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LATEST_ACTUAL_ANNUAL_DATA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HISTORICAL_DATA_SOURCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2027,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.941279,0.935937,0.969192,0.987751,0.999952,1.000000,0.999938,0.999787,0.999531,0.999199
2028,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.944484,0.939132,0.970663,0.988399,0.999785,0.999938,1.000000,0.999954,0.999804,0.999570
2029,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.947363,0.941950,0.971831,0.988822,0.999542,0.999787,0.999954,1.000000,0.999947,0.999801
2030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.950488,0.944959,0.973022,0.989195,0.999192,0.999531,0.999804,0.999947,1.000000,0.999953
2031,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.953341,0.947691,0.974042,0.989450,0.998773,0.999199,0.999570,0.999801,0.999953,1.000000

In [49]:
sheet3_df[2022].map(type).value_counts()

2022
<class 'float'>    75
Name: count, dtype: int64

In [50]:
for col in sheet3_df.columns:
    print(col)
    print(sheet3_df[col].map(type).value_counts())
    print()

DATASET
DATASET
<class 'str'>    75
Name: count, dtype: int64

SERIES_CODE
SERIES_CODE
<class 'str'>    75
Name: count, dtype: int64

COUNTRY.ID
COUNTRY.ID
<class 'str'>    75
Name: count, dtype: int64

COUNTRY
COUNTRY
<class 'str'>    75
Name: count, dtype: int64

INDICATOR.ID
INDICATOR.ID
<class 'str'>    75
Name: count, dtype: int64

INDICATOR
INDICATOR
<class 'str'>    75
Name: count, dtype: int64

INDICATOR.Description
INDICATOR.Description
<class 'str'>    75
Name: count, dtype: int64

FREQUENCY
FREQUENCY
<class 'str'>    75
Name: count, dtype: int64

SCALE
SCALE
<class 'str'>    75
Name: count, dtype: int64

UNIT
UNIT
<class 'str'>    75
Name: count, dtype: int64

COUNTRY_UPDATE_DATE
COUNTRY_UPDATE_DATE
<class 'float'>    75
Name: count, dtype: int64

PUBLICATION_DATE
PUBLICATION_DATE
<class 'pandas.Timestamp'>    75
Name: count, dtype: int64

UPDATE_DATE
UPDATE_DATE
<class 'str'>    75
Name: count, dtype: int64

METHODOLOGY
METHODOLOGY
<class 'float'>    75
Name: count, dtype: int64

METHODOLOGY_NOTES
METHODOLOGY_NOTES
<class 'float'>    75
Name: count, dtype: int64

LATEST_ACTUAL_ANNUAL_DATA
LATEST_ACTUAL_ANNUAL_DATA
<class 'float'>    75
Name: count, dtype: int64

HISTORICAL_DATA_SOURCE
HISTORICAL_DATA_SOURCE
<class 'float'>    75
Name: count, dtype: int64

BASE_YEAR
BASE_YEAR
<class 'float'>    75
Name: count, dtype: int64

START_END_MONTHS_OF_REPORTING_YEAR
START_END_MONTHS_OF_REPORTING_YEAR
<class 'float'>    75
Name: count, dtype: int64

CHAIN_WEIGHTED
CHAIN_WEIGHTED
<class 'float'>    75
Name: count, dtype: int64

BASIS_OF_PROJECTIONS
BASIS_OF_PROJECTIONS
<class 'float'>    75
Name: count, dtype: int64

VALUATION
VALUATION
<class 'float'>    75
Name: count, dtype: int64

PRICES_SECTOR_HARMONIZED_PRICES
PRICES_SECTOR_HARMONIZED_PRICES
<class 'float'>    75
Name: count, dtype: int64

LABOR_SECTOR_EMPLOYMENT_TYPE
LABOR_SECTOR_EMPLOYMENT_TYPE
<class 'float'>    75
Name: count, dtype: int64

FISCAL_SECTOR_GENERAL_GOVERNMENT_COMPOSITION
FISCAL_SECTOR_GENERAL_GOVERNMENT_COMPOSITION
<class 'float'>    75
Name: count, dtype: int64

FISCAL_SECTOR_VALUATION_OF_DEBT
FISCAL_SECTOR_VALUATION_OF_DEBT
<class 'float'>    75
Name: count, dtype: int64

FISCAL_SECTOR_INSTRUMENTS_INCLUDED_IN_GROSS_AND_NET_DEBT
FISCAL_SECTOR_INSTRUMENTS_INCLUDED_IN_GROSS_AND_NET_DEBT
<class 'float'>    75
Name: count, dtype: int64

TRADE_SECTOR_OIL_COVERAGE
TRADE_SECTOR_OIL_COVERAGE
<class 'float'>    75
Name: count, dtype: int64

PRIMARY_DOMESTIC_CURRENCY
PRIMARY_DOMESTIC_CURRENCY
<class 'float'>    75
Name: count, dtype: int64

1980
1980
<class 'float'>    75
Name: count, dtype: int64

1981
1981
<class 'float'>    75
Name: count, dtype: int64

1982
1982
<class 'float'>    75
Name: count, dtype: int64

1983
1983
<class 'float'>    75
Name: count, dtype: int64

1984
1984
<class 'float'>    75
Name: count, dtype: int64

1985
1985
<class 'float'>    75
Name: count, dtype: int64

1986
1986
<class 'float'>    75
Name: count, dtype: int64

1987
1987
<class 'float'>    75
Name: count, dtype: int64

1988
1988
<class 'float'>    75
Name: count, dtype: int64

1989
1989
<class 'float'>    75
Name: count, dtype: int64

1990
1990
<class 'float'>    75
Name: count, dtype: int64

1991
1991
<class 'float'>    75
Name: count, dtype: int64

1992
1992
<class 'float'>    75
Name: count, dtype: int64

1993
1993
<class 'float'>    75
Name: count, dtype: int64

1994
1994
<class 'float'>    75
Name: count, dtype: int64

1995
1995
<class 'float'>    75
Name: count, dtype: int64

1996
1996
<class 'float'>    75
Name: count, dtype: int64

1997
1997
<class 'float'>    75
Name: count, dtype: int64

1998
1998
<class 'float'>    75
Name: count, dtype: int64

1999
1999
<class 'float'>    75
Name: count, dtype: int64

2000
2000
<class 'float'>    75
Name: count, dtype: int64

2001
2001
<class 'float'>    75
Name: count, dtype: int64

2002
2002
<class 'float'>    75
Name: count, dtype: int64

2003
2003
<class 'float'>    75
Name: count, dtype: int64

2004
2004
<class 'float'>    75
Name: count, dtype: int64

2005
2005
<class 'float'>    75
Name: count, dtype: int64

2006
2006
<class 'float'>    75
Name: count, dtype: int64

2007
2007
<class 'float'>    75
Name: count, dtype: int64

2008
2008
<class 'float'>    75
Name: count, dtype: int64

2009
2009
<class 'float'>    75
Name: count, dtype: int64

2010
2010
<class 'float'>    75
Name: count, dtype: int64

2011
2011
<class 'float'>    75
Name: count, dtype: int64

2012
2012
<class 'float'>    75
Name: count, dtype: int64

2013
2013
<class 'float'>    75
Name: count, dtype: int64

2014
2014
<class 'float'>    75
Name: count, dtype: int64

2015
2015
<class 'float'>    75
Name: count, dtype: int64

2016
2016
<class 'float'>    75
Name: count, dtype: int64

2017
2017
<class 'float'>    75
Name: count, dtype: int64

2018
2018
<class 'float'>    75
Name: count, dtype: int64

2019
2019
<class 'float'>    75
Name: count, dtype: int64

2020
2020
<class 'float'>    75
Name: count, dtype: int64

2021
2021
<class 'float'>    75
Name: count, dtype: int64

2022
2022
<class 'float'>    75
Name: count, dtype: int64

2023
2023
<class 'float'>    75
Name: count, dtype: int64

2024
2024
<class 'float'>    75
Name: count, dtype: int64

2025
2025
<class 'float'>    75
Name: count, dtype: int64

2026
2026
<class 'float'>    75
Name: count, dtype: int64

2027
2027
<class 'float'>    75
Name: count, dtype: int64

2028
2028
<class 'float'>    75
Name: count, dtype: int64

2029
2029
<class 'float'>    75
Name: count, dtype: int64

2030
2030
<class 'float'>    75
Name: count, dtype: int64

2031
2031
<class 'float'>    75
Name: count, dtype: int64

In [51]:
mixed_cols = []

for col in sheet3_df.columns:
    if sheet3_df[col].dropna().map(type).nunique() > 1:
        mixed_cols.append(col)

mixed_cols

[]

In [52]:
sheet3_df.select_dtypes(exclude="number").columns

Index(['DATASET', 'SERIES_CODE', 'COUNTRY.ID', 'COUNTRY', 'INDICATOR.ID',
       'INDICATOR', 'INDICATOR.Description', 'FREQUENCY', 'SCALE', 'UNIT',
       'PUBLICATION_DATE', 'UPDATE_DATE'],
      dtype='object')

In [54]:
bad_values = sheet3_df[
    pd.to_numeric(sheet3_df[2022], errors="coerce").isna() 
    & sheet3_df[2022].notna()
][2022]

bad_values

Series([], Name: 2022, dtype: float64)

In [56]:
sheet3_df.shape()

TypeError: 'tuple' object is not callable

In [57]:
sheet3_df.describe()

,COUNTRY_UPDATE_DATE,METHODOLOGY,METHODOLOGY_NOTES,LATEST_ACTUAL_ANNUAL_DATA,HISTORICAL_DATA_SOURCE,BASE_YEAR,START_END_MONTHS_OF_REPORTING_YEAR,CHAIN_WEIGHTED,BASIS_OF_PROJECTIONS,VALUATION,...,2022,2023,2024,2025,2026,2027,2028,2029,2030,2031
count,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,75.000000,75.000000,75.000000,75.000000,75.000000,75.000000,75.000000,75.000000,75.000000,75.000000
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1414.316400,1268.371307,1329.015520,1341.127547,1619.610627,1633.307600,1637.479200,1643.158813,1650.275787,1656.835040
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4733.373635,4016.881662,4202.079699,4476.773707,6265.054241,6327.089624,6349.460374,6370.293381,6393.527683,6416.047024
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.751000,2.671000,2.418000,2.682000,1.896000,1.877000,1.822000,1.799000,1.799000,1.799000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,104.972500,95.096500,97.691500,95.771500,93.693000,93.285500,95.113500,95.524500,95.524500,95.524500
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,209.114000,165.648000,167.432000,164.599000,178.839000,176.395000,168.899000,167.382000,167.382000,167.382000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,545.635500,524.524500,485.193000,383.616000,431.384500,440.604500,436.013500,436.013500,436.013500,436.013500
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,31383.287000,25912.246000,30059.334000,34058.324000,50204.593000,50555.000000,50554.000000,50554.000000,50554.000000,50554.000000

3. Renaming Columns

In [ ]:
df.rename(columns={
    "WEO Country Code": "country_code",
    "Country": "country",
    "Subject Descriptor": "indicator"
}, inplace=True)

In [ ]:
df.columns = df.columns.astype(str).str.strip().str.lower().str.replace(" ", "_")

In [59]:
sheet1_df.isnull().sum()

DATASET            0
SERIES_CODE        0
COUNTRY.ID         0
COUNTRY            0
INDICATOR.ID       0
                ...
2027            1322
2028            1406
2029            1411
2030            1411
2031            1411
Length: 81, dtype: int64

In [60]:
sheet1_df.duplicated().sum()

np.int64(0)